figure_3_properties: &figure_3_properties
  x_tick_fontsize: 8
  y_label_fontsize: 10
  title_fontsize: 9
  text_fontsize: 10

s_figure_properties: &s_figure_properties
  x_label_fontsize: 12
  y_label_fontsize: 12
  title_fontsize: 12
  x_tick_fontsize: 10
  y_tick_fontsize: 10



version: 0.3.4
figure_palette:
  default_bar: black
  default_hist: lightgrey
  default_dot: dimgray
  dot_alpha: 0.8
  box_median_props:
    linewidth: 2
  cat_palette: colorblind
figure2:
  panels:
    panel_a:
      fig_size: [ 4.25 , 2.7 ]
      title: Diagnoses of Patients
      ylabel: Number of patients
      xlabel: Diagnosis
    panel_b:
      fig_size: [ 4.25 , 2.7 ]
      title: Age of Onset of CPVT Patients
      xlabel: Age of onset (years)
      ylabel: Number of patients
    panel_c:
      fig_size: [ 4.25 , 4.25 ]
      title: Age of Onset vs Incidence of PVT
      #xlabel: Condition
      xticklabels:
        False: No PVT
        True: PVT
      ylabel: Age of onset (years)
    panel_d:
      fig_size: [ 4.25, 4.25 ]
      title: Age of Onset vs Incidence of Syncope
      #xlabel: Condition
      xticklabels:
        False: No Syncope
        True: Syncope
      ylabel: Age of onset (years)
figure3:
  fig_size: [ 8.5, 5 ]
  panels:
    panel_a:
      title: Heart Structure Abnormality
      ylabel: Number of patients
      #xlabel: Condition
      xticklabels:
        False: "No heart\nstructure\nabnormality"
        #        False: "Normal"
        True: "Heart\nstructure\nabnormality"
      <<: *figure_3_properties
    panel_b:
      title: Exercise-induced PVT
      ylabel: Number of patients
      #xlabel: Condition
      xticklabels:
        False: No PVT
        True: PVT
      <<: *figure_3_properties
    panel_c:
      title: Exercise-induced Syncope
      ylabel: Number of patients
      #xlabel: Condition
      xticklabels:
        False: "No\nSyncope"
        True: Syncope
      <<: *figure_3_properties
    panel_d:
      title: Exercise-induced SCA
      ylabel: Number of patients
      #xlabel: Condition
      xticklabels:
        False: No SCA
        True: SCA
      <<: *figure_3_properties
    panel_e:
      title: Patient Sex
      ylabel: Number of patients
      #xlabel: Sex
      xticklabels:
        female: Female
        male: Male
      <<: *figure_3_properties
    panel_f:
      title: Inheritance
      ylabel: Number of variants
      #xlabel: Inheritance
      xticklabels:
        inherited: Inherited
        spontaneous: "de\nnovo"
      <<: *figure_3_properties
    panel_g:
      title: Family history of SCD
      ylabel: Number of patients
      #xlabel: Family history
      xticklabels:
        False: "No family\nhistory\nSCD"
        True: "Family\nhistory\nSCD"
      <<: *figure_3_properties
    panel_h:
      title: Abnormal ECG at Rest
      ylabel: Number of patients
      #xlabel: Condition
      xticklabels:
        False: "Normal"
        True: "Abnormal\nECG\nat rest"
      <<: *figure_3_properties
figure4:
  fig_size: [ 8.5, 3 ]
  panels:
    panel_a:
      title: Number of CPVT Patients by Variant, Top 20
      xlabel: Variant
      ylabel: Number of patients
    panel_b:
      title: Number of Substitution Variants by RYR2 Exon
      xlabel: Exon
      ylabel: Number of variants
    panel_c:
      title: Age of Onset by RYR2 Exon
      xlabel: Exon
      ylabel: Age of onset (years)
figure6:
  # NOTE: this is only for panels c, d
  fig_size: [ 8.5, 4.0 ]
  panels:
    panel_c:
      #      fig_size: [ 4.25, 4.25 ]
      title: Age of Onset by RYR2 Domain
      xlabel: Domain
      ylabel: Age of onset (years)
    panel_d:
      #      fig_size: [ 4.25, 4.5 ]
      title: Age of Onset by RYR2 Subdomain
      xlabel: Subdomain
      ylabel: Age of onset (years)
reviewer2_1:
  panels:
    panel_a:
      fig_size: [ 2.8, 2.8 ]
      title: "Age of Onset vs\nIncidence of PVT"
      #xlabel: Condition
      xticklabels:
        False: No PVT
        True: PVT
      ylabel: Age of onset (years)
    panel_b:
      fig_size: [ 2.8, 2.8 ]
      title: "Age of Onset vs\nIncidence of Syncope"
      #xlabel: Condition
      xticklabels:
        False: No Syncope
        True: Syncope
      ylabel: Age of onset (years)
    panel_c:
      fig_size: [ 2.8, 2.8 ]
      title: "Age of Onset vs\nIncidence of SCA"
      #xlabel: Condition
      xticklabels:
        False: No SCA
        True: SCA
      ylabel: Age of onset (years)
s_figure_2:
  fig_size: [ 3.5, 3.5 ]
  title: "Age of Onset for\nMissense and Non-missense Variants"
  #  xlabel: Treatment
  ylabel: Age of onset (years)
  <<: *s_figure_properties
s_figure_3:
  fig_size: [ 6.5, 3.75 ]
  title: Additional Treatment Strategies for CPVT Patients on Beta-blockers
  xlabel: Treatment
  ylabel: Number of patients
  <<: *s_figure_properties
s_figure_4:
  figure_size: [ 6.5, 3 ]
  title: Number of Patients with Atrial Tachycardia by Exon
  xlabel: Exon
  ylabel: Number of patients
  <<: *s_figure_properties
s_figure_treatments:
  panels:
    bb_vs_non_bb:
      fig_size: [ 2.8333, 3.5 ]
      title: "Beta-blocker Treatment"
      ylabel: Number of patients
      <<: *s_figure_properties
    pharmacological_treatment:
      fig_size: [ 2.8333, 3.5 ]
      title: "Pharmacological Treatment"
      ylabel: Number of patients
      <<: *s_figure_properties
    invasive_treatment:
      fig_size: [ 2.8333, 3.5 ]
      title: "Invasive Treatment"
      ylabel: Number of patients
      <<: *s_figure_properties
graphic_abstract:
  panels:
    bb_pct:
      fig_size: [ 3.5, 4 ]
    age_onset_vs_symptoms:
      fig_size: [ 3.25, 4 ]
      title: "Age of Onset vs\nIncidence of Syncope"
      xticklabels:
        False: No Syncope
        True: Syncope
      ylabel: Age of onset (years)
treatment_pcts:
  panels:
    flecainide_pct:
      fig_size: [ 4.25, 4.25 ]
      #      title: "Flecainide Treatment\nin CPVT Patients"
      xlabel: "Variant"
      ylabel: "Percentage of patients"
    icd_pct:
      fig_size: [ 4.25, 4.25 ]
      #      title: "ICD Treatment\nin CPVT Patients"
      xlabel: "Variant"
      ylabel: "Percentage of patients"



