name: cpvt_database_analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - jupyter
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - openpyxl
  - scipy
  - tqdm
  - pyarrow
  - scikit-learn
  - scikit-posthocs
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - conda-forge::r-base
  - conda-forge::r-renv
  - conda-forge::r-irkernel
  - conda-forge::r-tidyverse
  - conda-forge::r-essentials
  - conda-forge::r-here
  - conda-forge::r-rstatix
  - conda-forge::r-effectsize
  - conda-forge::r-tidyverse
  - pip:
      - sqlalchemy
      - psycopg[binary]
      - pydantic-settings
      - pydantic
      - duckdb
      - pyyaml
      - reportlab
      # pip install cpvt-database-models --index-url https://gitlab.com/api/v4/projects/60969577/packages/pypi/simple
