name: cpvt_database_analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - jupyter
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - openpyxl
  - scipy
  - tqdm
  - pyarrow
  - scikit-learn
  - scikit-posthocs
  - r-base
  - r-essentials
  - r-here
  - r-rstatix
  - r-effectsize
  - pip:
      - sqlalchemy
      - psycopg[binary]
      - pydantic-settings
      - pydantic
      - duckdb
      - pyyaml
      - cpvt-database-models --index-url https://gitlab.com/api/v4/projects/60969577/packages/pypi/simple
